#requires custom_templates/electricity_price.jinja
#requires packages/electricity_price.yaml

#region Nord Pool
# docs: https://www.home-assistant.io/integrations/nordpool
# device: [device_id]                                                   <-- TODO: replace all occurrences with your device id (see README.md)
# sensor: sensor.nord_pool_se4_current_price                            <-- TODO: replace all occurrences with name of your sensor for your area
# config_entry: [config_entry_id]                                       <-- TODO: replace all occurrences with your config entry id (see README.md)
# setup:
#   Electricity price -┬-------------> nord_pool_additional_cost --------┐
#                      |                                                 |
#   Nord Pool ---------┼-[schedule]--> nord_pool_price_api -┬-[schedule]-┴--> nord_pool_price -┬--> nord_pool_price_cheap
#                      |                                    |                                  └--> nord_pool_price_expensive
#                      └------------------------------------┼--> nord_pool_price_api_status
#                                                           └--> nord_pool_price_unavailable
#endregion

input_number:
  # TODO (optional): set to additional cost on top of spot price (excl.
  # VAT) if using Nord Pool as the source sensor for electricity price
  nord_pool_additional_cost:
    name: Nord Pool additional cost
    min: 0.0
    max: 100.0
    step: 0.01
    mode: box
    unit_of_measurement: öre/kWh
    icon: mdi:cash-multiple

template:
  - trigger:
      - trigger: time_pattern
        minutes: 30
        id: "time_pattern"
      - trigger: homeassistant
        event: start
        id: "home_assistant_startup"
      - platform: event
        event_type: call_service
        event_data:
          domain: template
          service: reload
        id: "template_reload"
      - trigger: state
        entity_id: binary_sensor.nord_pool_price_api_status
        to: "on"
        from: "off"
        id: "price_api_status"
      # temporary trigger to handle switch to 15 min pricing
      - trigger: template
        value_template: >
          {% if is_state('binary_sensor.nord_pool_price_api_status', 'on') %}
            {% set interval = state_attr('sensor.nord_pool_price_api', 'interval') %}
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set index = state_attr('sensor.nord_pool_price', 'current_price_api_index') | int(0) %}
            {% set current_interval = (prices[index + 1].start | as_datetime(now().min|as_local)
              - prices[index].start | as_datetime(now().min|as_local)).total_seconds() | int %}
            {{ not interval == current_interval }}
          {% endif %}
        id: "price_interval_change"
    # only trigger on 'time_pattern' after 13 (until we have tomorrow's prices)
    conditions: >
      {{ (trigger.id == 'time_pattern'
          and is_state_attr('binary_sensor.nord_pool_price_api_status', 'tomorrows_prices_available', false)
              and 13 <= now().hour <= 23 )
          or trigger.id != 'time_pattern' }}
    action:
      - action: nordpool.get_prices_for_date
        data:
          config_entry: [config_entry_id]
          date: "{{ now().date() }}"
        response_variable: today_prices
      - action: nordpool.get_prices_for_date
        data:
          config_entry: [config_entry_id]
          date: "{{ now().date() + timedelta(days=1) }}"
        response_variable: tomorrow_prices
    sensor:
      # TODO: replace all occurrences of 'SE4' below with name of your area
      - name: Nord Pool price API
        state: &start >
          {{ (today_prices.SE4[0].start | as_datetime(now().min|as_local)).isoformat() }}
        device_class: timestamp
        unique_id: nord_pool_price_api
        icon: mdi:api
        availability: >
          {{ today_prices is mapping and today_prices.SE4 | length > 0 }}
        attributes:
          sensor_updated_by: >
            {{ trigger.id | replace('_', ' ') | title }} at {{ now().strftime('%H:%M:%S') }}
          start: *start
          end: >
            {% set prices = today_prices.SE4 + tomorrow_prices.SE4 %}
            {{ (prices[-1].end | as_datetime(now().min|as_local)).isoformat() }}
          interval: >
            {% set prices = today_prices.SE4 %}
            {{ (prices[1].start | as_datetime(now().min|as_local)
              - prices[0].start | as_datetime(now().min|as_local)).total_seconds() | int }}
          prices: >
            {{ today_prices.SE4 + tomorrow_prices.SE4 }}

  - trigger:
      - trigger: time_pattern
        minutes: 0
        id: "time_pattern"
      - trigger: state
        entity_id: sensor.nord_pool_price_api
        id: "price_api"
      - trigger: state
        entity_id: sensor.nord_pool_additional_cost
        to:
        id: "additional_cost"
    # only update if 'nord_pool_price_api' is valid
    conditions: >
      {{ is_state('binary_sensor.nord_pool_price_api_status', 'on') }}
    sensor:
      - name: Nord Pool price
        state: &current_price >
          {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
          {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
          {% from 'electricity_price.jinja' import electricity_price_current %}
          {# returned price is per MWh, without VAT or added costs #}
          {% set current_price = electricity_price_current(prices,
            span = span,
            __is_nord_pool__ = true) %}
          {{ current_price }}
        unit_of_measurement: SEK/kWh
        state_class: total
        device_class: monetary
        unique_id: nord_pool_price
        icon: mdi:cash-multiple
        availability: >
          {{ has_value('sensor.nord_pool_price_api') }}
        attributes:
          sensor_updated_by: >
            {{ trigger.id | replace('_', ' ') | title }} at {{ now().strftime('%H:%M:%S') }}
          avg_price: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% from 'electricity_price.jinja' import electricity_price_avg %}
            {{ electricity_price_avg(prices,
              __is_nord_pool__ = true) }}
          price_percent_to_average: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_current, electricity_price_avg %}
            {% set current_price = electricity_price_current(prices,
              span = span,
              __is_nord_pool__ = true) | float %}
            {% set avg_price = electricity_price_avg(prices,
              __is_nord_pool__ = true) | float %}
            {{ ((current_price / avg_price) * 100) | round(0, default=0) }}
          price_above_average: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_current, electricity_price_avg %}
            {% set current_price = electricity_price_current(prices,
              span = span,
              __is_nord_pool__ = true) | float %}
            {% set avg_price = electricity_price_avg(prices,
              __is_nord_pool__ = true) | float %}
            {{ current_price > avg_price }}
          price_level: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_current, electricity_price_avg, electricity_price_level %}
            {% set current_price = electricity_price_current(prices,
              span = span,
              __is_nord_pool__ = true) | float %}
            {% set avg_price = electricity_price_avg(prices,
              __is_nord_pool__ = true) | float %}
            {{ electricity_price_level(current_price, avg_price) }}
          today: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_transform %}
            {{ electricity_price_transform(prices,
              span = span,
              as_list = true,
              __is_nord_pool__ = true) }}
          tomorrow: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_transform %}
            {{ electricity_price_transform(prices,
              span = span,
              date = now().date() + timedelta(days=1),
              as_list = true,
              __is_nord_pool__ = true) }}
          tomorrow_avg_price: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% from 'electricity_price.jinja' import electricity_price_avg %}
            {{ electricity_price_avg(prices,
              date = now().date() + timedelta(days=1),
              __is_nord_pool__ = true) }}
          prices: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_transform %}
            {{ electricity_price_transform(prices,
              span = span,
              date = none,
              __is_nord_pool__ = true) }}
          current_price_api_index: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% for i in prices %}
                {% set time = i.start | as_datetime | as_local %}
                {% if time == today_at(now().strftime("%H:00")) %}
                  {{ loop.index0 }}
                  {% break %}
                {% endif %}
            {% endfor %}
          current_price: *current_price
          current_price_spot: >
            {% set prices = state_attr('sensor.nord_pool_price_api', 'prices') %}
            {% set span = (3600 / state_attr('sensor.nord_pool_price_api', 'interval')) | int %}
            {% from 'electricity_price.jinja' import electricity_price_current %}
            {{ electricity_price_current(prices,
              divider = 1000,
              span = span,
              time_attribute = 'start') }}

  - sensor:
      - name: Nord Pool additional cost
        state: >
          {# user defined additional cost #}
          {% set additional_cost = states('input_number.nord_pool_additional_cost') | float * 0.01 %}

          {% if states('input_select.electricity_price_sensor') != 'sensor.nord_pool_price' %}
            {#
              default to current sensor state
              https://community.home-assistant.io/t/this-state-in-template-sensor-not-working-at-all/857176/7
            #}
            {% set additional_cost = this.state
              if not this is none
                and this.state is defined
                and this.state | is_number
              else additional_cost %}

            {% if has_value('sensor.electricity_price')
              and has_value('sensor.nord_pool_price')
              and (states.sensor.electricity_price.last_updated | as_local).hour
                == (states.sensor.nord_pool_price.last_updated | as_local).hour %}
              {% set vat = 1 + (states('input_number.electricity_price_vat') | int * 0.01) %}
              {% set additional_cost = states('sensor.electricity_price') | float
                - state_attr('sensor.nord_pool_price', 'current_price_spot') | float * vat %}
            {% endif %}
          {% endif %}

          {# output additional cost #}
          {{ additional_cost | round(3, default=0) }}
        unit_of_measurement: SEK/kWh
        state_class: total
        device_class: monetary
        unique_id: nord_pool_additional_cost
        icon: mdi:cash-multiple
        attributes:
          electricity_price_sensor: "{{ states('input_select.electricity_price_sensor') }}"
          electricity_price: "{{ states('sensor.electricity_price') }}"
          electricity_price_last_updated: "{{ states.sensor.electricity_price.last_updated | as_local }}"
          nord_pool_price: "{{ states('sensor.nord_pool_price') }}"
          nord_pool_price_spot: "{{ state_attr('sensor.nord_pool_price', 'current_price_spot') }}"
          nord_pool_price_last_updated: "{{ states.sensor.nord_pool_price.last_updated | as_local }}"
          nord_pool_additional_cost: "{{ (states('input_number.nord_pool_additional_cost') | float * 0.01) | round(3, default=0) }}"

  - binary_sensor:
      - name: Nord Pool price API status
        state: &todays_prices_available >
          {% set start = state_attr('sensor.nord_pool_price_api', 'start') | as_datetime(now().min|as_local) %}
          {% set end = state_attr('sensor.nord_pool_price_api', 'end') | as_datetime(now().min|as_local) %}
          {{ start < now() < end }}
        device_class: connectivity
        unique_id: nord_pool_price_api_status
        availability: >
          {{ has_value('sensor.nord_pool_price_api') }}
        attributes:
          todays_prices_available: *todays_prices_available
          tomorrows_prices_available: >
            {% set end = state_attr('sensor.nord_pool_price_api', 'end') | as_datetime(now().min|as_local) %}
            {{ end == today_at() + timedelta(days=2) }}
          nord_pool_price_api_start: "{{ state_attr('sensor.nord_pool_price_api', 'start') }}"
          nord_pool_price_api_end: "{{ state_attr('sensor.nord_pool_price_api', 'end') }}"

      - name: Nord Pool price cheap
        state: >
          {% set prices = state_attr('sensor.nord_pool_price', 'prices') %}
          {% from 'electricity_price.jinja' import electricity_price_current_is_outlier %}
          {{ electricity_price_current_is_outlier(prices) }}
        device_class: power
        unique_id: nord_pool_price_cheap
        availability: >
          {{ has_value('sensor.nord_pool_price') }}
        attributes:
          today: >
            {% set prices = state_attr('sensor.nord_pool_price', 'prices') %}
            {% from 'electricity_price.jinja' import electricity_price_outliers %}
            {{ electricity_price_outliers(prices) }}
          tomorrow: >
            {% set prices = state_attr('sensor.nord_pool_price', 'prices') %}
            {% from 'electricity_price.jinja' import electricity_price_outliers %}
            {{ electricity_price_outliers(prices,
              date = now().date() + timedelta(days=1)) }}
          electricity_price_threshold: "{{ states('sensor.electricity_price_threshold') }}"
          electricity_price_cheap_hours: "{{ states('sensor.electricity_price_cheap_hours') }}"

      - name: Nord Pool price expensive
        state: >
          {% set prices = state_attr('sensor.nord_pool_price', 'prices') %}
          {% from 'electricity_price.jinja' import electricity_price_current_is_outlier %}
          {{ electricity_price_current_is_outlier(prices,
            cheap = false) }}
        device_class: power
        unique_id: nord_pool_price_expensive
        availability: >
          {{ has_value('sensor.nord_pool_price') }}
        attributes:
          today: >
            {% set prices = state_attr('sensor.nord_pool_price', 'prices') %}
            {% from 'electricity_price.jinja' import electricity_price_outliers %}
            {{ electricity_price_outliers(prices,
              cheap = false) }}
          tomorrow: >
            {% set prices = state_attr('sensor.nord_pool_price', 'prices') %}
            {% from 'electricity_price.jinja' import electricity_price_outliers %}
            {{ electricity_price_outliers(prices,
              cheap = false,
              date = now().date() + timedelta(days=1)) }}
          electricity_price_threshold: "{{ states('sensor.electricity_price_threshold') }}"
          electricity_price_expensive_hours: "{{ states('sensor.electricity_price_expensive_hours') }}"

      - name: Nord Pool unavailable
        state: >
          {{ not (
            has_value('sensor.nord_pool_se4_current_price')
            and has_value('sensor.nord_pool_price_api')
            and is_state('binary_sensor.nord_pool_price_api_status', 'on')) }}
        delay_on: 0:02:00 # turn on if problem persists for 2 minutes
        device_class: problem
        unique_id: nord_pool_unavailable
        attributes:
          nord_pool_se4_current_price: "{{ states('sensor.nord_pool_se4_current_price') }}"
          nord_pool_price_api: "{{ states('sensor.nord_pool_price_api') }}"
          nord_pool_price_api_status: "{{ states('binary_sensor.nord_pool_price_api_status') }}"

automation:
  - id: nord_pool_watchdog
    alias: Nord Pool watchdog
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.nord_pool_unavailable
        to: "on"
        from: "off"
    actions:
      - repeat:
          until:
            - condition: state
              entity_id: binary_sensor.nord_pool_unavailable
              state: "off"
          sequence:
            - action: homeassistant.reload_config_entry
              target:
                device_id:
                  - [device_id]
            - wait_template: >-
                {{ is_state('binary_sensor.nord_pool_unavailable', 'off') }}
              timeout: "00:04:00"
    mode: restart
