template:
  - binary_sensor:
      - name: Z-Wave addon up and running
        state: >
          {{ is_state('binary_sensor.z_wave_js_ui_running', 'on')
            and states('sensor.alive_z_wave_devices') | int(0) > 0 }}
        delay_on: 0:02:00 # turn on after 2 minutes to allow time for loading nodes
        icon: mdi:z-wave
        device_class: running
        unique_id: z_wave_addon_up_and_running

  - trigger:
      - trigger: time_pattern
        seconds: /30
    sensor:
      - name: Dead Z-Wave devices
        icon: mdi:z-wave
        state: >
          {% if this.attributes.entity_id != none %}
            {{ this.attributes.entity_id | length }}
          {% else %}
            {# no dead devices identified #}
            0
          {% endif %}
        unit_of_measurement: entities
        unique_id: dead_z_wave_devices
        attributes:
          entity_id: >-
            {% set nodes = integration_entities('zwave_js') | select('match', 'sensor\..*_node_status') | select('is_state', ['dead', 'unavailable', 'unknown']) | list %}
            {% set ns = namespace(buttons=[]) %}
            {% for e in nodes %}
              {% set device_id = device_id(e) %}
              {% set button = device_entities(device_id) | select('match','button\..*_ping') | first %}
              {% set ns.buttons = ns.buttons + [button] %}
            {% endfor %}
            {{ ns.buttons }}

      - name: Alive Z-Wave devices
        icon: mdi:z-wave
        state: >
          {% if this.attributes.entity_id != none %}
            {{ this.attributes.entity_id | length }}
          {% else %}
            {# no alive devices identified #}
            0
          {% endif %}
        unit_of_measurement: entities
        unique_id: alive_z_wave_devices
        attributes:
          entity_id: >-
            {{ integration_entities('zwave_js') | select('match', 'sensor\..*_node_status') | select('is_state', ['alive']) | list }}

input_boolean:
  enable_z_wave_problem_detection:
    name: Enable Z-Wave problem detection
    initial: true
    icon: mdi:z-wave

script:
  ping_all_z_wave_devices:
    alias: Ping all Z-Wave devices
    icon: mdi:z-wave
    description: Ping all Z-Wave devices in the network
    sequence:
      - condition: template
        value_template: >
          {{ integration_entities('zwave_js') | select('match', 'button\..*_ping') | list | length > 0 }}
      - action: button.press
        target:
          entity_id: >
            {{ integration_entities('zwave_js') | select('match', 'button\..*_ping') | list }}
    mode: queued

  trigger_all_z_wave_automations:
    alias: Trigger all Z-Wave automations
    icon: mdi:z-wave
    description: Trigger all automations involving Z-Wave devices
    sequence:
      - action: automation.trigger
        data:
          skip_condition: false
        target:
          entity_id:
            - automation.outdoor_lights
            - ...
    mode: queued

automation:
  - id: ping_dead_z_wave_devices
    alias: Ping dead Z-Wave devices
    description: ""
    triggers:
      - trigger: state
        entity_id: sensor.dead_z_wave_devices
      - trigger: state
        entity_id: binary_sensor.z_wave_addon_up_and_running
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_z_wave_problem_detection
        state: "on"
      - condition: state
        entity_id: binary_sensor.z_wave_addon_up_and_running
        state: "on"
      - condition: template
        value_template: >
          {{ states('sensor.dead_z_wave_devices') | int(0) > 0 }}
    actions:
      - repeat:
          until:
            - condition: numeric_state
              entity_id: sensor.dead_z_wave_devices
              below: 1
          sequence:
            - action: button.press
              target:
                entity_id: "{{ state_attr('sensor.dead_z_wave_devices', 'entity_id') }}"
            - wait_template: >-
                {{ states('sensor.dead_z_wave_devices') | int < 1 }}
              timeout: "00:00:30"
    mode: restart
    trace:
      stored_traces: 20

  - id: dead_z_wave_device_back
    alias: Z-Wave devices back from the dead
    description: ""
    triggers:
      - trigger: state
        entity_id: sensor.dead_z_wave_devices
    conditions:
      - condition: state
        entity_id: input_boolean.enable_z_wave_problem_detection
        state: "on"
      - condition: state
        entity_id: binary_sensor.z_wave_addon_up_and_running
        state: "on"
      - condition: template
        value_template: >
          {{ trigger.from_state.state | int(0) > trigger.to_state.state | int(0) }}
    actions:
      - action: script.trigger_all_z_wave_automations
    mode: restart
    trace:
      stored_traces: 20

  - id: z_wave_error_detected
    alias: Z-Wave error detected
    description: ""
    triggers:
      - trigger: event
        event_type: system_log_event
        event_data:
          level: ERROR
    conditions:
      - condition: state
        entity_id: input_boolean.enable_z_wave_problem_detection
        state: "on"
      - condition: or
        conditions:
          - condition: template
            value_template: >
              {% set components = [
                'homeassistant.components.zwave_js',
                'homeassistant.components.script.turn_on_zwave_switch_group',
                'homeassistant.components.script.turn_off_zwave_switch_group',
                'homeassistant.components.script.turn_on_zwave_light_group',
                'homeassistant.components.script.turn_off_zwave_light_group'
              ] %}
              {{ trigger.event.data.name in components }}
          - condition: template
            value_template: >
              {{ 'zwave_js_server.exceptions.Failed' in trigger.event.data.exception }}
      - condition: not
        conditions:
          - condition: template
            value_template: >
              {{ 'While executing automation' in (trigger.event.data.message | join('|')) }}
    actions:
      - delay:
          seconds: 30 # cool down period if there are multiple, related, errors in log
      - action: script.trigger_all_z_wave_automations
    mode: restart
    trace:
      stored_traces: 20

  - id: z_wave_addon_restart
    alias: Z-Wave addon restart
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id: sensor.alive_z_wave_devices
        below: 1
        for:
          minutes: 10
    conditions:
      - condition: state
        entity_id: input_boolean.enable_z_wave_problem_detection
        state: "on"
    actions:
      - action: hassio.addon_restart
        data:
          addon: a0d7b954_zwavejs2mqtt
    mode: single

  - id: z_wave_addon_startup
    alias: Z-Wave addon start-up
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.z_wave_addon_up_and_running
        to: "on"
        from: "off"
    conditions:
      - condition: state
        entity_id: input_boolean.enable_z_wave_problem_detection
        state: "on"
    actions:
      - action: script.trigger_all_z_wave_automations
    mode: single
